version: '3'
services:

  postgres:
    image: postgres

    ports:
      - '5432:5432'
    network_mode: bridge
    container_name: car_assistent_db

    environment:
      POSTGRES_USER: 'car_assistent'
      POSTGRES_PASSWORD: 'car_assistent'
      POSTGRES_DB: 'car_assistent'

    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d